project:
  type: website

lang: en

website:
  title: PWHL Fantasy League
  back-to-top-navigation: true
  page-navigation: true

  site-url: https://alex-and-noah.github.io/pwhl-fantasy-league/
  repo-url: https://github.com/Alex-and-Noah/pwhl-fantasy-league
  repo-actions: [issue, source]

  navbar:
    background: primary
    search: true
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Standings"
        href: team_standings.qmd
      - text: "Fantasy Rosters"
        href: fantasy_rosters.qmd
      - text: "PWHL Rosters"
        href: pwhl_rosters.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Team Generator"
        href: team_generator.qmd
      - text: "Info"
        href: draft_info.qmd
    right:
    - icon: git
      menu:
        - text: Source code
          url: https://github.com/Alex-and-Noah/pwhl-fantasy-league
        - text: Report an issue
          url:  https://github.com/Alex-and-Noah/pwhl-fantasy-league/-/issues/new

format: 
  html:
    logo: logo.svg
    nav-buttons: 
      - icon: github
        href: https://github.com/Alex-and-Noah/pwhl-fantasy-league
    theme:
      - brand
      - styles.scss
    toc: true
    html-table-processing: none

execute:
  freeze: auto