# Draft Info

## Row

::: {.card title="Rules"}
Choose your fantasy team name, colour, logo and roster in the [Google Sheet](https://docs.google.com/spreadsheets/d/1sywjZ6quCmbLBq_wEEXZEDzcW0NeBpCtRaT3W1hDkhI/edit?usp=sharing). (If you want some inspiration for your draft, you can check out the [team generator](#team-generator))<br>
&nbsp;&nbsp;&nbsp;&nbsp;🔴🟡🔵**Team Colour:** Valid hexadecimal colour code<br>
&nbsp;&nbsp;&nbsp;&nbsp;👩‍👩‍👧📷🖥️**Team Image:** Valid link to any image on the web<br><br>
Your team should have exactly the following (the Google Sheet dropdowns force this structure, don't worry!):<br>
&nbsp;&nbsp;&nbsp;&nbsp;**🏒 6 forwards**<br>
&nbsp;&nbsp;&nbsp;&nbsp;**🛡️ 4 defenders**<br>
&nbsp;&nbsp;&nbsp;&nbsp;**🥅 2 goalies**<br><br>
😮‍💨 Players/goalies aren't restricted to a single fantasy team so if someone took a player you like, you can take them too!<br><br>
↔️ **Trades:** Throughout the season, you are allowed **exactly 1 trade** (respecting the team structure). Your new player only contributes points to your fantasy score starting the day after the trade. Please **let Alex or Noah know directly** if/when you make a trade!<br><br>
🕐 **Deadline:** You can use all of November's pre-season and regular season games to scout your roster and aim to lock it in by **November 30th, 2025**! After this date, the Google Sheet will be 👁️**View Only**👁️<br><br>
💰💵💸 **Prize pool (Optional):** E-transfer $10 to Alex or Noah to enter in the fantasy prize pool! More information TBD but you could **WIN BIGGGG! (Send an e-transfer or intent to e-transfer by the roster deadline to enter the prize pool)**
:::

## Row

::: {.card title="Scoring"}
Your fantasy team's score is updated daily with data from the previous day's games. Each day, each member of your fantasy roster will contribute a number of points to your team's overall score, following the scheme below:

🏒 1 point per goal<br>
🤝 1 point per assist<br>
✨ 2 points per win\*<br>
😖 0 points per loss\*<br>
🥇 1 point per OT loss\*

You can check how your and everyone else's teams are doing [here](#team-standings). Note that eventually, only **regular season games** will contribute to your fantasy teams score.

\*Note that if your play did not play in a game in which their team won, they will *not* contribute points to your score (this includes dressed goalies that did not get subbed in).
:::