# Schedule

## Row {.tabset}

```{r "schedule"}
#| title: "Regular season"
current_schedule |>
  left_join(
    team_info |>
      rename_with(
        ~paste0(
          "home_",
          .
        )
      ) |>
      select(
        home_team_id,
        home_team_logo
      ),
    by = "home_team_id"
  ) |> left_join(
    team_info |>
      rename_with(
        ~paste0(
          "away_",
          .
        )
      ) |>
      select(
        away_team_id,
        away_team_logo
      ),
    by = "away_team_id"
  ) |>
  select(
    c(
      game_date,
      game_status,
      away_team_logo,
      away_score,
      home_team_logo,
      home_score
    )
  ) |>
  mutate(
    game_date = as.Date(
      game_date,
      format = "%Y-%m-%d"
    ) |>
      format(
        "%a, %b %e"
      )
  ) |>
  gt() |>
  fmt_image(
    columns = c(
      away_team_logo,
      home_team_logo
    )
  ) |>
  cols_align(
    align = "center",
    columns = c(
      game_status,
      away_score,
      home_score
    )
  ) |>
  cols_width(
    game_date ~ pct(20),
    game_status ~ pct(20),
    away_team_logo ~ pct(10),
    away_score ~ pct(10),
    home_team_logo ~ pct(10),
    home_score ~ pct(10)
  ) |>
  cols_label(
    game_date = "Date",
    game_status = "Time",
    away_team_logo = "Away",
    away_score = "Score",
    home_team_logo = "Home",
    home_score = "Score"
  ) |>
  tab_options(
    table.background.color = "#F5F5F5",
    column_labels.background.color = "#2B2D42",
    table.font.size = px(16),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table_body.hlines.color = "transparent",
    table_body.border.bottom.color = "transparent",
    column_labels.border.bottom.color = "transparent",
    column_labels.border.top.color = "transparent"
  ) |>
  tab_style_body(
    style = cell_borders(
      sides = c("top", "right", "left", "bottom"),
      weight = px(0) # Remove row borders
    ),
    fn = function(x) {
      is.numeric(x) | is.character(x)
    }
  ) |>
  opt_css(
    css = "

    table tr:nth-child(odd) {
      background-color: #e0dedeff;
    }

    .gt_col_heading {
      position: sticky !important;
      top: 0px !important;
      z-index: 10 !important;
    }
    "
  )
```

```{r "schedule preseason"}
#| title: "Pre-season"
# schedule_preseason |>
#   select(
#     c(
#       game_date,
#       game_status,
#       away_team_logo,
#       away_score,
#       home_team_logo,
#       home_score
#     )
#   ) |>
#   mutate(
#     game_date = as.Date(
#       game_date,
#       format = "%Y-%m-%d"
#     ) |>
#       format(
#         "%a, %b %e"
#       )
#   ) |>
#   gt() |>
#   fmt_image(
#     columns = c(
#       away_team_logo,
#       home_team_logo
#     )
#   ) |>
#   cols_align(
#     align = "center",
#     columns = c(
#       game_status,
#       away_score,
#       home_score
#     )
#   ) |>
#   cols_width(
#     game_date ~ pct(20),
#     game_status ~ pct(20),
#     away_team_logo ~ pct(10),
#     away_score ~ pct(10),
#     home_team_logo ~ pct(10),
#     home_score ~ pct(10)
#   ) |>
#   cols_label(
#     game_date = "Date",
#     game_status = "Time",
#     away_team_logo = "Away",
#     away_score = "Score",
#     home_team_logo = "Home",
#     home_score = "Score"
#   ) |>
#   tab_options(
#     table.background.color = "#F5F5F5",
#     column_labels.background.color = "#2B2D42",
#     table.font.size = px(16),
#     table.border.top.color = "transparent",
#     table.border.bottom.color = "transparent",
#     table_body.hlines.color = "transparent",
#     table_body.border.bottom.color = "transparent",
#     column_labels.border.bottom.color = "transparent",
#     column_labels.border.top.color = "transparent"
#   ) |>
#   tab_style_body(
#     style = cell_borders(
#       sides = c("top", "right", "left", "bottom"),
#       weight = px(0) # Remove row borders
#     ),
#     fn = function(x) {
#       is.numeric(x) | is.character(x)
#     }
#   ) |>
#   opt_css(
#     css = "

#     table tr:nth-child(odd) {
#       background-color: #e0dedeff;
#     }

#     .gt_col_heading {
#       position: sticky !important;
#       top: 0px !important;
#       z-index: 10 !important;
#     }
#     "
#   )
```
