---
execute:
  echo: false
  warning: false
  error: false
---

```{r "imports"}
library(here)
library(purrr)
library(knitr)
library(gt)
library(dplyr)

invisible(
  lapply(
    list.files(
      "./R",
      full.names = TRUE
    ),
    source
  )
)
fantasy_teams <- readRDS(
  here("data","fantasy_teams.rds")
)

team_info <- readRDS(
  here("data","team_info.rds")
)

standings <- readRDS(
  here("data","standings.rds")
)
```

::: {.panel-tabset}

```{r "team rosters"}
#| output: asis
res <- purrr::map_chr(
  names(fantasy_teams),
  function(fantasy_team_name) {
    knitr::knit_child(
      text = c(
        "## `r fantasy_team_name`",
        "",
        "```{r}",
        "#| echo: false",
        "html(",
        "    web_image(",
        "        url = standings |>",
        "          filter(",
        "            fantasy_team_name == .env$fantasy_team_name",
        "          ) |>",
        "          select(",
        "            team_image",
        "          ) |>",
        "          pull(),",
        "        height = '50px'",
        "    )",
        ")",
        "",
        "generate_pwhl_roster_gt_table(",
        "    fantasy_team_name,",
        "    fantasy_teams,",
        "    team_info",
        ")",
        "",
        "```",
        "",
        ""
      ),
      envir = environment(),
      quiet = TRUE
    )
  }
)

cat(res, sep = '\n')
```
:::