# Team Standings

## Row {.tabset}

```{r "standings over time", fig.width=12,fig.height=5}
#| title: "Regular Season"
if (
  current_schedule |>
    filter(
      game_status %in%
        c(
          "Final",
          "Final OT"
        )
    ) |>
    nrow() ==
    0
) {
  value_box(
    title = "No data available",
    showcase = bs_icon(
      "hourglass-split",
      size = "6vh"
    ),
    value = tags$p(
      "No games played yet this season",
      style = "font-size: 4vh;"
    ),
    theme = "danger"
  )
} else {
  data <- standings |>
    select(
      -c(
        fantasy_points,
        position_change_since_yesterday,
        fantasy_points_change_since_yesterday
      )
    ) |>
    pivot_longer(
      !c(
        team_colour,
        team_image,
        fantasy_team_name
      ),
      names_to = NULL,
      values_to = "standings"
    ) |>
    arrange(
      desc(
        row_number()
      )
    )|>
    group_by(
      by = fantasy_team_name
    ) |>
    mutate(
      day_number = row_number()
    ) |>
    ungroup()

  data |>
    ggplot() +
    geom_line(
      aes(
        x = day_number,
        y = standings,
        colour = team_colour
      ),
      linewidth = 2
    ) +
    geom_point(
      data = data |>
        filter(
          day_number == max(day_number)
        ),
      aes(
        x = day_number,
        y = standings,
        colour = team_colour
      ),
      size = 15
    ) +
    geom_image(
      data = data |>
        filter(
          day_number == max(day_number)
        ),
      aes(
        x = day_number,
        y = standings,
        image = team_image
      )
    ) +
    scale_color_identity() +
    scale_y_reverse() +
    guides(
      colour = guide_legend(
        override.aes = list(
          size = 10
        )
      )
    ) + 
    theme_minimal() +
    theme(
      axis.text.y = element_blank(),
      plot.background = element_rect(
        fill = "#e0e0e0"
      )
    )
}
```

## Row {.tabset}

```{r "standings full"}
#| title: "Regular season"
standings |>
  mutate(
    fantasy_points = round(
      fantasy_points,
      2
    ),
    position_change_since_yesterday = case_when(
      position_change_since_yesterday == "-1" ~ "arrow-down",
      position_change_since_yesterday == "0" ~ NA,
      position_change_since_yesterday == "1" ~ "arrow-up"
    )
  ) |>
  select(
    team_colour,
    team_image,
    fantasy_team_name,
    fantasy_points,
    position_change_since_yesterday,
    fantasy_points_change_since_yesterday
  ) |>
  arrange(
    desc(
      fantasy_points
    )
  ) |>
  gt() |>
  fmt_icon(
    columns = position_change_since_yesterday,
    fill_color = c(
      "arrow-up" = "#128800ff",
      "arrow-down" = "#c50101ff",
      height = "1.5em"
    )
  ) |>
  text_transform(
    locations = cells_body(
      columns = team_image
    ),
    fn = function(x) {
      web_image(
        url = x,
        height = "5vh"
      )
    }
  ) |>
  tab_style(
    style = list(
      cell_fill(
        color = from_column(
          column = "team_colour"
        )
      ),
      cell_text(
        weight = "bold"
      )
    ),
    locations = cells_body(
      columns = team_image
    )
  ) |>
  cols_hide(
    c(
      team_colour,
      position_change_since_yesterday,
      fantasy_points_change_since_yesterday
    )
  ) |>
  cols_label(
    team_image = "",
    fantasy_team_name = "Team Name",
    fantasy_points = "Points"
  ) |>
  cols_align(
    columns = everything(),
    align = "center"
  ) |>
  sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = ""
  ) |>
  tab_options(
    table.background.color = "#F5F5F5",
    column_labels.background.color = "#2B2D42",
    table.font.size = px(16),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table_body.hlines.color = "transparent",
    table_body.border.bottom.color = "transparent",
    column_labels.border.bottom.color = "transparent",
    column_labels.border.top.color = "transparent"
  ) |>
  tab_style_body(
    style = cell_borders(
      sides = c("top", "right", "left", "bottom"),
      weight = px(0) # Remove row borders
    ),
    fn = function(x) {
      is.numeric(x) | is.character(x)
    }
  ) |>
  opt_css(
    css = "

    table tr:nth-child(odd) {
      background-color: #e0dedeff;
    }

    .gt_col_heading {
      position: sticky !important;
      top: 0px !important;
      z-index: 10 !important;
    }
    "
  )
```